### ISSUE TITLE
卒業制作 issueベースの開発

### ISSUE THREAD

**Issue by jannah-n** [jannah-n/graduation_exam#12]
■Webアプリの概要
お子様対象の計10問の簡単な質問に答え、どの程度の内容まで理解できるか確認するクイズ形式のアプリです。
正解の場合は次の質問へ進むことができ、間違った場合は今やった質問がそのまま表示されます。
MVPリリースの時点では基礎的なユーザー登録、認証機能、2歳~3歳を対象にした計10問のクイズを出題する機能を
実装しようと考えています。本リリースの時点ではユーザー登録機能に「年齢」「性別」カラムを追加し、ユーザーに
「年齢」「性別」に応じてクイズをおすすめする機能等を追加、クイズ一覧画面を作成し「年齢」「性別」「テーマ」に
応じたクイズを随時更新していきたいと考えています。

■1週間辺りの開発に向けられる時間
- 1週間あたり：10~20時間(1日にどれだけ隙間時間を確保できるかによって左右される為)

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
https://github.com/users/jannah-n/projects/1

■MVPリリースまで
- [ ] 環境構築
- [ ] rails new
- [ ] mainブランチにデプロイ
- [ ] トップ画面
- [ ] ユーザー登録画面
- [ ] ユーザー認証画面
- [ ] ユーザー登録機能
- [ ] ログイン/ログアウト機能
- [ ] クイズ(2歳~3歳対象)計10問出題機能

■MVP後
- [ ] ユーザー登録機能に「年齢」「性別」カラムを追加
- [ ] 「年齢」「性別」に応じてユーザーに合ったクイズを表示するおすすめ機能
- [ ] クイズ一覧画面
- [ ] クイズ一覧画面に「年齢」「性別」「テーマ」に応じたクイズを随時更新
- [ ] ユーザー管理画面(ユーザーの「詳細」「編集」「削除」を可能にする)
- [ ] パスワード、メールアドレス変更機能(letter_opener)

■MVPレビュー依頼予定日
予定日：2024年 11月 4日

**Comment by Mariko222** [comment]
ご提出ありがとうございます。
以下、気になった点のコメントになります。
***
- ストーリーポイントが4以上のカードがいくつか見受けられましたので、カリキュラムに記載通り、ストーリーポイント3以下になるように細分化していただきたいです。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
- 仮にデプロイエラーになった際に、実装のどの段階が原因か把握しやすいと思いますので、`rails new`直後の早い段階でのデプロイ作業が推奨されています。
こちら追加で、デプロイのカード作成もお願いします。

**Comment by jannah-n** [comment]
Mariko様

お世話になっております。
レビューいただき、ありがとうございます!!

ご指摘いただいた内容に合わせて、Projects内のスケジュール及び
issueの内容を編集させていただきました。

編集箇所は以下の通りです。

①Projects内のスケジュールのカードでストーリーポイントを4に設定していたものを3以下になるようカードを細分化

②rails new直後にmainブランチにデプロイする内容のカードをスケジュール内に追加

③issue内のMVPリリースまでに実施する内容に「mainブランチにデプロイ」を項目追加

お手数おかけしますが、ご確認の程宜しくお願い致します。

**Comment by kenchasonakai** [comment]
LGTMです！
