### ISSUE TITLE
卒業制作 MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by jannah-n** [jannah-n/graduation_exam#33]
## 各種情報

- サービスの概要とMVPで検証する事柄：

ユーザー登録、認証機能を持つ子供向けのクイズアプリです。
MVPリリースの時点では基礎的なユーザー登録機能(「ユーザー名」「メールアドレス」「パスワード」「パスワード確認」)、
ユーザー認証機能(「メールアドレス」「パスワード」)、クイズ出題機能(2歳から3歳対象、計10問)を実装しました。

- サービス名：

QUIZ-APP(現時点でいい名前が思いつかない為、仮の名前です)

- サービスURL：

GitHubのURL : https://github.com/jannah-n/graduation_exam
デプロイ先URL : https://graduation-exam.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [x] 基礎的なユーザー登録機能(「ユーザー名」「メールアドレス」「パスワード」「パスワード確認」を入力し、登録)

※ユーザー登録画面
[![Image from Gyazo](https://i.gyazo.com/df4b85701fe78f734b7c8c56e71ed5ec.png)](https://gyazo.com/df4b85701fe78f734b7c8c56e71ed5ec)

※ユーザー登録失敗の場合(そのままユーザー登録画面を表示し「ユーザー登録できませんでした」とエラーメッセージを表示)
[![Image from Gyazo](https://i.gyazo.com/27d93dd959b766ad56c3cf73011618f7.png)](https://gyazo.com/27d93dd959b766ad56c3cf73011618f7)

※ユーザー登録成功の場合(トップ画面を表示し「ユーザー登録できました」とメッセージを表示)
[![Image from Gyazo](https://i.gyazo.com/80fcd9ae066d36a913d0f8105166bfcc.png)](https://gyazo.com/80fcd9ae066d36a913d0f8105166bfcc)

- [x] 基礎的なユーザー認証機能(「メールアドレス」「パスワード」を入力し、ログイン)

※ユーザー認証画面
[![Image from Gyazo](https://i.gyazo.com/1da9e579b922f1dbb58d2d198fe9b1f7.png)](https://gyazo.com/1da9e579b922f1dbb58d2d198fe9b1f7)

※ユーザー認証失敗の場合(そのままユーザー認証画面を表示し「ログインできませんでした」とメッセージを表示)
[![Image from Gyazo](https://i.gyazo.com/65160bc59c3aa6df7d07b5e4b7f8aec7.png)](https://gyazo.com/65160bc59c3aa6df7d07b5e4b7f8aec7)

※ユーザー認証成功の場合(クイズ開始画面を表示し「ログインできました」とメッセージを表示)
[![Image from Gyazo](https://i.gyazo.com/ac9f645b3f7361ccdd14a45fbe5f1176.png)](https://gyazo.com/ac9f645b3f7361ccdd14a45fbe5f1176)

※クイズ終了後にログアウトした場合(トップ画面を表示し「ログアウトしました」とメッセージを表示)
[![Image from Gyazo](https://i.gyazo.com/28fd6e3f85ed973ccf0231761210af69.png)](https://gyazo.com/28fd6e3f85ed973ccf0231761210af69)

- [x] クイズ(2歳から3歳対象、計10問)出題機能

※クイズ開始画面
[![Image from Gyazo](https://i.gyazo.com/b8ea97e4288c8293e78b95e6f58e87a5.png)](https://gyazo.com/b8ea97e4288c8293e78b95e6f58e87a5) 

※以下のようなクイズを計10問ランダムに表示
[![Image from Gyazo](https://i.gyazo.com/352123cfed9295f22c49defc03331baf.png)](https://gyazo.com/352123cfed9295f22c49defc03331baf)

※回答を間違えた場合(同じクイズを表示し「不正解です(T_T)」とメッセージを表示)
[![Image from Gyazo](https://i.gyazo.com/551f9485b52d215307723587aeac5471.png)](https://gyazo.com/551f9485b52d215307723587aeac5471)

※回答が正解の場合(次のクイズを表示し「正解しました!!」とメッセージを表示)
[![Image from Gyazo](https://i.gyazo.com/d375dde3f8ef8661d381b537b350f04c.png)](https://gyazo.com/d375dde3f8ef8661d381b537b350f04c)

※10問目を終えるとクイズ終了画面を表示
[![Image from Gyazo](https://i.gyazo.com/abd3fdaa432554c40c82ff01b21e9fca.png)](https://gyazo.com/abd3fdaa432554c40c82ff01b21e9fca)

## READMEレビュー時から変更した機能

- ユーザー登録、認証機能実装の際、devise機能を使用する旨を記載していましたが結局不使用
- Gem bcryptedをインストールし、Usersテーブルのencrypted_passwordをpassword_digestにカラム名を変更
- ユーザー登録失敗時にバリデーションエラー(日本語化は未実施)を表示

※バリデーションエラーの日本語化やページの見た目調整等は本リリースまでに実施します

## サービスイメージがわかるようなスクリーンショット等

①まずはアプリトップ画面の「ユーザー登録」を開き、ユーザー情報を登録
[![Image from Gyazo](https://i.gyazo.com/45f6a936ffb126a19dea094aa0801e49.png)](https://gyazo.com/45f6a936ffb126a19dea094aa0801e49)

[![Image from Gyazo](https://i.gyazo.com/54d3f83eae003ad56aab0008dd121345.png)](https://gyazo.com/54d3f83eae003ad56aab0008dd121345)

②ユーザー登録完了後「ログイン」を開き、ログイン
[![Image from Gyazo](https://i.gyazo.com/9e0479b5a7cab4b1bf5486c5f5b77254.png)](https://gyazo.com/9e0479b5a7cab4b1bf5486c5f5b77254)

[![Image from Gyazo](https://i.gyazo.com/57e419ed75f60864d5e9a82e00c138a4.png)](https://gyazo.com/57e419ed75f60864d5e9a82e00c138a4)

[![Image from Gyazo](https://i.gyazo.com/43b55ed25182061c3076443e73c6d8cc.png)](https://gyazo.com/43b55ed25182061c3076443e73c6d8cc)

③ログイン完了後「START」ボタンを押し、クイズを開始
[![Image from Gyazo](https://i.gyazo.com/43b55ed25182061c3076443e73c6d8cc.png)](https://gyazo.com/43b55ed25182061c3076443e73c6d8cc)

※以下のようなクイズを10問回答する
[![Image from Gyazo](https://i.gyazo.com/a7a7ce8cda7ec0da2fd97349f103abbe.png)](https://gyazo.com/a7a7ce8cda7ec0da2fd97349f103abbe)

④10問回答後、クイズ終了画面が表示されたらログアウト
[![Image from Gyazo](https://i.gyazo.com/ca3bde0db1006a10454d3aa7bae1a2d0.png)](https://gyazo.com/ca3bde0db1006a10454d3aa7bae1a2d0)

[![Image from Gyazo](https://i.gyazo.com/5a925ae060a23cf8c68be94697a2afa8.png)](https://gyazo.com/5a925ae060a23cf8c68be94697a2afa8)

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

現状、まだMVPの段階なので、改善点などは色々な方に使ってもらって感想をもらうことで、より良いアプリになると思います！

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
